application: minetegneserier
version: 1
api_version: 1
runtime: python

handlers:
- url: /comic/.*
  script: handlers/picturehandler.py
- url: /create
  script: handlers/createhandler.py
- url: .*
  script: handlers/mainhandler.py