application: minetegneserier
version: 1
api_version: 1
runtime: python

handlers:
- url: /comic/.*
  script: handlers/picturehandler.py
- url: /update
  script: handlers/updatehandler.py
  login: admin
- url: .*
  script: handlers/mainhandler.py