application: minetegneserier
version: 1
api_version: 1
runtime: python

handlers:
- url: /comic/.*
  script: handlers/picturehandler.py
- url: /setup
  script: handlers/setuphandler.py
- url: /test
  script: handlers/testhandler.py
- url: .*
  script: handlers/mainhandler.py